### ISSUE TITLE
Missing ApplyDamageOptions

### ISSUE THREAD

**Issue by GniLudio** [ModDota/TypeScriptAddonTemplate#6]
This is the definition of `ApplyDamage`:
```typescript
declare function ApplyDamage(options: ApplyDamageOptions): number;
```

It would be nice to be able to look up what should be inside `ApplyDamageOptions`:
https://moddota.com/api/#!/vscripts?search=ApplyDamage

```
ApplyDamageOptions
    victim: CDOTA_BaseNPC
    attacker: CDOTA_BaseNPC
    damage: float
    damage_type: DAMAGE_TYPES
    damage_flags?: DOTADamageFlag_t
    ability?: CDOTABaseAbility
```

**Comment by Perryvw** [comment]
Just type ApplyDamageOptions, rightclick it and 'Go To Definition'

**Comment by GniLudio** [comment]
I tried that, but it didn't work.
Now it's working...
